# Generated by Django 3.1.7 on 2021-03-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField()),
                ('noofpieces', models.IntegerField()),
                ('image', models.ImageField(default='image.jpg', upload_to='products')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
