# Generated by Django 3.1.7 on 2021-03-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='no',
            field=models.IntegerField(default=0),
        ),
    ]
