# Generated by Django 3.1.7 on 2021-03-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemcat', models.CharField(blank=True, choices=[['SH', 'shirts'], ['BG', 'bags'], ['SO', 'shoes'], ['JK', 'jackets']], max_length=10, null=True)),
            ],
        ),
    ]
