# Generated by Django 3.1.7 on 2021-03-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('SH', 'shirt'), ('SO', 'shoes'), ('BG', 'bags'), ('JK', 'jackets'), ('PT', 'piants')], max_length=10, null=True),
        ),
    ]
